export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_ORDER = 'FETCH_ORDER';
export const PURCHACE_BURGER_START = 'PURCHACE_BURGER_START';
export const GET_ORDERS = 'GET_ORDERS';
export const IS_GETTING_ORDERS = 'IS_GETTING_ORDERS'